# Visit https://golangci-lint.run/ for usage documentation and information on other useful linters
version: "2"
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - "go/*"
linters:
  default: standard
  enable:
    - durationcheck
    - errcheck
    - copyloopvar
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet
