name: testing

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code into the Go module directory
        # https://github.com/actions/checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
        id: go
      - name: Get dependencies
        run: |
          go mod download
          sudo apt-get install -y xorriso
      - name: Build
        run: |
          go build -v .
  unit:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        # https://github.com/actions/checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
      - run: go test -v -cover ./...
  test:
    name: Integration Tests (${{ matrix.tool }} / Cobbler ${{ matrix.cobbler_version }})
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool:
          - terraform
          - opentofu
        cobbler_version:
          - 2f0ff03f17ae957cac65d9ef033a98e8d597145a # v4.0.0a4
      fail-fast: false
    steps:
      - name: Check out code into the Go module directory
        # https://github.com/actions/checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
        id: go
      - name: Set up Terraform
        if: matrix.tool == 'terraform'
        # https://github.com/hashicorp/setup-terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      - name: Set up OpenTofu
        if: matrix.tool == 'opentofu'
        # https://github.com/opentofu/setup-opentofu
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
      - name: Export TF_ACC_TERRAFORM_PATH for OpenTofu
        if: matrix.tool == 'opentofu'
        run: echo "TF_ACC_TERRAFORM_PATH=$(which tofu)" >> "$GITHUB_ENV"
      - name: Install system dependencies
        run: |
          sudo apt-get install -y xorriso
      - name: Get dependencies
        run: |
          go mod download
      - name: Replace git version hash
        run: |
          sed -i "s/cobbler_commit=.*/cobbler_commit=${{ matrix.cobbler_version }}/" docker/start.sh
      - name: Restore OS ISO
        id: cache-iso-restore
        # https://github.com/actions/cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            *.iso
          key: ${{ runner.os }}-${{ matrix.cobbler_version }}-iso
      - name: Make Test
        env:
          TF_ACC_PROVIDER_NAMESPACE: cobbler
        run: |
          make testacc
      - name: Save OS ISO
        id: cache-iso-save
        # https://github.com/actions/cache
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            *.iso
          key: ${{ steps.cache-iso-restore.outputs.cache-primary-key }}
      - name: Upload coverage report to GH artifacts
        if: matrix.cobbler_version == 'TODO_4_0_X_COMMIT' && matrix.tool == 'terraform'
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-report
          path: coverage.out
          if-no-files-found: error
